# Generated by Django 5.0.6 on 2024-06-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_model',
            new_name='Customers',
        ),
        migrations.RenameModel(
            old_name='doctor',
            new_name='Doctors',
        ),
    ]
