# Generated by Django 5.0.6 on 2024-06-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
    ]
