# Generated by Django 5.0.6 on 2024-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0010_customgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission', verbose_name='permissions'),
        ),
    ]
