# Generated by Django 5.0.6 on 2024-06-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customgroup_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, unique=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customgroup')),
            ],
        ),
    ]
