# Generated by Django 5.0.6 on 2024-06-30 09:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cashboxlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_of_service',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
