# Generated by Django 5.0.6 on 2024-06-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_service_priceprice_of_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='priceprice_of_service',
        ),
    ]
