# Generated by Django 5.0.6 on 2024-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_service_priceprice_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
