# Generated by Django 5.0.6 on 2024-07-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0017_alter_customers_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='main_users_set', related_query_name='main_user', to='auth.group'),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='main_users_permissions_set', related_query_name='main_user', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='username',
            field=models.CharField(default='superuser', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='mainusers',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
