# Generated by Django 5.0.6 on 2024-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_mainusers_groups_mainusers_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='mainusers',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
