# Generated by Django 5.0.6 on 2024-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0021_alter_mainusers_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='mainusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='main_users_permissions_set', related_query_name='main_user', to='main.customgroup'),
        ),
    ]
