# Generated by Django 5.0.6 on 2024-07-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0022_alter_mainusers_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='mainusers_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='mainusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='mainusers_permissions', to='auth.permission'),
        ),
    ]
