# Generated by Django 5.0.6 on 2024-07-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_mainusers_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainusers',
            name='role',
        ),
    ]
