from django.contrib import admin
from django.urls import path
from main.views import *
from docs.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', login_view, name='login'),
    path('orders/', allOrders, name='allOrders'),
    path('orders/create/', createOrder, name='create-order'),
    path('doctors/available/<int:service_id>/', getAvailableDoctors, name='available-doctors'),
    path('api/orders/<int:pk>/', delete_order, name='delete-order'),
    path('api/orders/update/<int:pk>/', update_order, name='order-update'),
    path('api/services/create', addService, name='add-service'),
    path('api/services/all', getAllServices, name='get-all-services'),
    path('api/services/delete/<int:pk>', deleteService, name='delete-service'),
    path('api/services/update/<int:pk>', updateService, name='update-service'),
    path('api/doctors/create', addDoctor, name='add-doctor'),
    path('api/doctors/all', getAllDoctors, name='get-all-doctors'),
    path('api/doctors/delete/<int:pk>', deleteDoctor, name='delete-doctor'),
    path('api/doctors/update/<int:pk>', updateDoctor, name='update-doctor'),
    path('api/user/logout', logout_view, name="logout"),
    path('api/cashbox/all', showCashBox, name='cashbox-all'),
    path('api/cashbox/total/', getTotal, name='total-price'),
    path('api/cashbox/reset', reset_cashbox, name='resetCashbox'),
    path('api/cashbox/withdrawCashbox', withdraw_money, name='withdraw'),
    path('api/create-user', createUser, name='create-user'),
    path('api/users/all', allUsers, name="all-users"),
    path('api/customers/list', allCustomers, name="allCustomers"),
    path('api/customers/create', createCustomer, name="createCustomer"),
    path('api/customers/update/<int:pk>', updateCustomer, name="updateCustomer"),
    path('api/customers/delete/<int:pk>', deleteCustomer, name="deleteCustomer"),
    path('api/users/delete/<int:pk>', deleteUser, name="deleteUser"),
    path('api/users/update/<int:pk>', updateUser, name="updateUser"),
    path('api/categories/all', AllCategory, name="AllCategory"),
    path('api/categories/delete/<int:pk>', deleteCategory, name="deleteCategory"),
    path('api/categories/create/', createCategory, name="createCategory"),
    path('api/categories/update/<int:pk>', updateCategory, name="updateCategory"),
    path('api/roles/all', allRoles, name="allRoles"),
    path('api/roles/update/<int:pk>', editRole, name="editRole"),
    path('api/roles/delete/<int:pk>', deleteRole, name="deleteRole"),
    path('api/roles/create', createRole, name="createRole"),
    path('permissions/', listPermissions, name='list-permissions'),
    path('', home, name='home')
]
